# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sliceable-transceiver-sdm-service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sliceable-transceiver-sdm-service.proto',
  package='sliceable_transceiver_sdm_service',
  syntax='proto3',
  serialized_pb=_b('\n\'sliceable-transceiver-sdm-service.proto\x12!sliceable_transceiver_sdm_service\"\x07\n\x05\x65mpty\"1\n\x0e\x66requency_slot\x12\x0b\n\x03ncf\x18\x01 \x01(\x05\x12\x12\n\nslot_width\x18\x02 \x01(\r\"F\n\x0c\x65qualization\x12\x16\n\x0e\x65qualizationid\x18\x01 \x01(\t\x12\x0c\n\x04mimo\x18\x02 \x01(\x08\x12\x10\n\x08num_taps\x18\x03 \x01(\r\"\xee\x02\n\x0eoptical_signal\x12\x18\n\x10opticalchannelid\x18\x01 \x01(\t\x12V\n\rconstellation\x18\x02 \x01(\x0e\x32?.sliceable_transceiver_sdm_service.optical_signal.Constellation\x12\x11\n\tbandwidth\x18\x03 \x01(\x04\x12\x42\n\x03\x66\x65\x63\x18\x04 \x01(\x0e\x32\x35.sliceable_transceiver_sdm_service.optical_signal.Fec\x1a\x0e\n\x0c\x65qualization\x1a+\n\x07monitor\x12\x0c\n\x04osnr\x18\x02 \x01(\x01\x1a\x12\n\x03\x62\x65r\x12\x0b\n\x03\x62\x65r\x18\x01 \x01(\x01\"9\n\rConstellation\x12\t\n\x05qam64\x10\x00\x12\t\n\x05qam16\x10\x01\x12\x08\n\x04qam4\x10\x02\x12\x08\n\x04qpsk\x10\x03\"\x1b\n\x03\x46\x65\x63\x12\t\n\x05hdfec\x10\x00\x12\t\n\x05sdfec\x10\x01\"]\n\x0foptical_channel\x12\x18\n\x10opticalchannelid\x18\x01 \x01(\t\x12\x0e\n\x06\x63oreid\x18\x02 \x01(\t\x12\x0e\n\x06modeid\x18\x03 \x01(\t\x1a\x10\n\x0e\x66requency_slot\"7\n\x05slice\x1a\t\n\x07sliceid\x1a\x11\n\x0foptical_channel\x1a\x10\n\x0eoptical_signal\"\x1a\n\x07sliceid\x12\x0f\n\x07sliceid\x18\x01 \x01(\t\"-\n\x0btransceiver\x12\x15\n\rtransceiverid\x18\x01 \x01(\t\x1a\x07\n\x05slice\"3\n\x11transceiver_state\x12\x15\n\rtransceiverid\x18\x01 \x01(\t\x1a\x07\n\x05slice2\xfb\x01\n\x12TransceiverService\x12l\n\x0eSetTransceiver\x12..sliceable_transceiver_sdm_service.transceiver\x1a(.sliceable_transceiver_sdm_service.empty\"\x00\x12w\n\x06GetBer\x12*.sliceable_transceiver_sdm_service.sliceid\x1a=.sliceable_transceiver_sdm_service.optical_signal.monitor.ber\"\x00\x30\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_OPTICAL_SIGNAL_CONSTELLATION = _descriptor.EnumDescriptor(
  name='Constellation',
  full_name='sliceable_transceiver_sdm_service.optical_signal.Constellation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='qam64', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='qam16', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='qam4', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='qpsk', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=491,
  serialized_end=548,
)
_sym_db.RegisterEnumDescriptor(_OPTICAL_SIGNAL_CONSTELLATION)

_OPTICAL_SIGNAL_FEC = _descriptor.EnumDescriptor(
  name='Fec',
  full_name='sliceable_transceiver_sdm_service.optical_signal.Fec',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='hdfec', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='sdfec', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=550,
  serialized_end=577,
)
_sym_db.RegisterEnumDescriptor(_OPTICAL_SIGNAL_FEC)


_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='sliceable_transceiver_sdm_service.empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=85,
)


_FREQUENCY_SLOT = _descriptor.Descriptor(
  name='frequency_slot',
  full_name='sliceable_transceiver_sdm_service.frequency_slot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ncf', full_name='sliceable_transceiver_sdm_service.frequency_slot.ncf', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slot_width', full_name='sliceable_transceiver_sdm_service.frequency_slot.slot_width', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=136,
)


_EQUALIZATION = _descriptor.Descriptor(
  name='equalization',
  full_name='sliceable_transceiver_sdm_service.equalization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='equalizationid', full_name='sliceable_transceiver_sdm_service.equalization.equalizationid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mimo', full_name='sliceable_transceiver_sdm_service.equalization.mimo', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_taps', full_name='sliceable_transceiver_sdm_service.equalization.num_taps', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=208,
)


_OPTICAL_SIGNAL_EQUALIZATION = _descriptor.Descriptor(
  name='equalization',
  full_name='sliceable_transceiver_sdm_service.optical_signal.equalization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=152,
)

_OPTICAL_SIGNAL_MONITOR_BER = _descriptor.Descriptor(
  name='ber',
  full_name='sliceable_transceiver_sdm_service.optical_signal.monitor.ber',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ber', full_name='sliceable_transceiver_sdm_service.optical_signal.monitor.ber.ber', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=489,
)

_OPTICAL_SIGNAL_MONITOR = _descriptor.Descriptor(
  name='monitor',
  full_name='sliceable_transceiver_sdm_service.optical_signal.monitor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='osnr', full_name='sliceable_transceiver_sdm_service.optical_signal.monitor.osnr', index=0,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_OPTICAL_SIGNAL_MONITOR_BER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=489,
)

_OPTICAL_SIGNAL = _descriptor.Descriptor(
  name='optical_signal',
  full_name='sliceable_transceiver_sdm_service.optical_signal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opticalchannelid', full_name='sliceable_transceiver_sdm_service.optical_signal.opticalchannelid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='constellation', full_name='sliceable_transceiver_sdm_service.optical_signal.constellation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bandwidth', full_name='sliceable_transceiver_sdm_service.optical_signal.bandwidth', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fec', full_name='sliceable_transceiver_sdm_service.optical_signal.fec', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_OPTICAL_SIGNAL_EQUALIZATION, _OPTICAL_SIGNAL_MONITOR, ],
  enum_types=[
    _OPTICAL_SIGNAL_CONSTELLATION,
    _OPTICAL_SIGNAL_FEC,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=577,
)


_OPTICAL_CHANNEL_FREQUENCY_SLOT = _descriptor.Descriptor(
  name='frequency_slot',
  full_name='sliceable_transceiver_sdm_service.optical_channel.frequency_slot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=103,
)

_OPTICAL_CHANNEL = _descriptor.Descriptor(
  name='optical_channel',
  full_name='sliceable_transceiver_sdm_service.optical_channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='opticalchannelid', full_name='sliceable_transceiver_sdm_service.optical_channel.opticalchannelid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coreid', full_name='sliceable_transceiver_sdm_service.optical_channel.coreid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modeid', full_name='sliceable_transceiver_sdm_service.optical_channel.modeid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_OPTICAL_CHANNEL_FREQUENCY_SLOT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=672,
)


_SLICE_SLICEID = _descriptor.Descriptor(
  name='sliceid',
  full_name='sliceable_transceiver_sdm_service.slice.sliceid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=683,
  serialized_end=692,
)

_SLICE_OPTICAL_CHANNEL = _descriptor.Descriptor(
  name='optical_channel',
  full_name='sliceable_transceiver_sdm_service.slice.optical_channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=596,
)

_SLICE_OPTICAL_SIGNAL = _descriptor.Descriptor(
  name='optical_signal',
  full_name='sliceable_transceiver_sdm_service.slice.optical_signal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=227,
)

_SLICE = _descriptor.Descriptor(
  name='slice',
  full_name='sliceable_transceiver_sdm_service.slice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_SLICE_SLICEID, _SLICE_OPTICAL_CHANNEL, _SLICE_OPTICAL_SIGNAL, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=674,
  serialized_end=729,
)


_SLICEID = _descriptor.Descriptor(
  name='sliceid',
  full_name='sliceable_transceiver_sdm_service.sliceid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sliceid', full_name='sliceable_transceiver_sdm_service.sliceid.sliceid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=731,
  serialized_end=757,
)


_TRANSCEIVER_SLICE = _descriptor.Descriptor(
  name='slice',
  full_name='sliceable_transceiver_sdm_service.transceiver.slice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=674,
  serialized_end=681,
)

_TRANSCEIVER = _descriptor.Descriptor(
  name='transceiver',
  full_name='sliceable_transceiver_sdm_service.transceiver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transceiverid', full_name='sliceable_transceiver_sdm_service.transceiver.transceiverid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TRANSCEIVER_SLICE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=759,
  serialized_end=804,
)


_TRANSCEIVER_STATE_SLICE = _descriptor.Descriptor(
  name='slice',
  full_name='sliceable_transceiver_sdm_service.transceiver_state.slice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=674,
  serialized_end=681,
)

_TRANSCEIVER_STATE = _descriptor.Descriptor(
  name='transceiver_state',
  full_name='sliceable_transceiver_sdm_service.transceiver_state',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transceiverid', full_name='sliceable_transceiver_sdm_service.transceiver_state.transceiverid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TRANSCEIVER_STATE_SLICE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=806,
  serialized_end=857,
)

_OPTICAL_SIGNAL_EQUALIZATION.containing_type = _OPTICAL_SIGNAL
_OPTICAL_SIGNAL_MONITOR_BER.containing_type = _OPTICAL_SIGNAL_MONITOR
_OPTICAL_SIGNAL_MONITOR.containing_type = _OPTICAL_SIGNAL
_OPTICAL_SIGNAL.fields_by_name['constellation'].enum_type = _OPTICAL_SIGNAL_CONSTELLATION
_OPTICAL_SIGNAL.fields_by_name['fec'].enum_type = _OPTICAL_SIGNAL_FEC
_OPTICAL_SIGNAL_CONSTELLATION.containing_type = _OPTICAL_SIGNAL
_OPTICAL_SIGNAL_FEC.containing_type = _OPTICAL_SIGNAL
_OPTICAL_CHANNEL_FREQUENCY_SLOT.containing_type = _OPTICAL_CHANNEL
_SLICE_SLICEID.containing_type = _SLICE
_SLICE_OPTICAL_CHANNEL.containing_type = _SLICE
_SLICE_OPTICAL_SIGNAL.containing_type = _SLICE
_TRANSCEIVER_SLICE.containing_type = _TRANSCEIVER
_TRANSCEIVER_STATE_SLICE.containing_type = _TRANSCEIVER_STATE
DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['frequency_slot'] = _FREQUENCY_SLOT
DESCRIPTOR.message_types_by_name['equalization'] = _EQUALIZATION
DESCRIPTOR.message_types_by_name['optical_signal'] = _OPTICAL_SIGNAL
DESCRIPTOR.message_types_by_name['optical_channel'] = _OPTICAL_CHANNEL
DESCRIPTOR.message_types_by_name['slice'] = _SLICE
DESCRIPTOR.message_types_by_name['sliceid'] = _SLICEID
DESCRIPTOR.message_types_by_name['transceiver'] = _TRANSCEIVER
DESCRIPTOR.message_types_by_name['transceiver_state'] = _TRANSCEIVER_STATE

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'sliceable_transceiver_sdm_service_pb2'
  # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.empty)
  ))
_sym_db.RegisterMessage(empty)

frequency_slot = _reflection.GeneratedProtocolMessageType('frequency_slot', (_message.Message,), dict(
  DESCRIPTOR = _FREQUENCY_SLOT,
  __module__ = 'sliceable_transceiver_sdm_service_pb2'
  # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.frequency_slot)
  ))
_sym_db.RegisterMessage(frequency_slot)

equalization = _reflection.GeneratedProtocolMessageType('equalization', (_message.Message,), dict(
  DESCRIPTOR = _EQUALIZATION,
  __module__ = 'sliceable_transceiver_sdm_service_pb2'
  # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.equalization)
  ))
_sym_db.RegisterMessage(equalization)

optical_signal = _reflection.GeneratedProtocolMessageType('optical_signal', (_message.Message,), dict(

  equalization = _reflection.GeneratedProtocolMessageType('equalization', (_message.Message,), dict(
    DESCRIPTOR = _OPTICAL_SIGNAL_EQUALIZATION,
    __module__ = 'sliceable_transceiver_sdm_service_pb2'
    # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.optical_signal.equalization)
    ))
  ,

  monitor = _reflection.GeneratedProtocolMessageType('monitor', (_message.Message,), dict(

    ber = _reflection.GeneratedProtocolMessageType('ber', (_message.Message,), dict(
      DESCRIPTOR = _OPTICAL_SIGNAL_MONITOR_BER,
      __module__ = 'sliceable_transceiver_sdm_service_pb2'
      # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.optical_signal.monitor.ber)
      ))
    ,
    DESCRIPTOR = _OPTICAL_SIGNAL_MONITOR,
    __module__ = 'sliceable_transceiver_sdm_service_pb2'
    # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.optical_signal.monitor)
    ))
  ,
  DESCRIPTOR = _OPTICAL_SIGNAL,
  __module__ = 'sliceable_transceiver_sdm_service_pb2'
  # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.optical_signal)
  ))
_sym_db.RegisterMessage(optical_signal)
_sym_db.RegisterMessage(optical_signal.equalization)
_sym_db.RegisterMessage(optical_signal.monitor)
_sym_db.RegisterMessage(optical_signal.monitor.ber)

optical_channel = _reflection.GeneratedProtocolMessageType('optical_channel', (_message.Message,), dict(

  frequency_slot = _reflection.GeneratedProtocolMessageType('frequency_slot', (_message.Message,), dict(
    DESCRIPTOR = _OPTICAL_CHANNEL_FREQUENCY_SLOT,
    __module__ = 'sliceable_transceiver_sdm_service_pb2'
    # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.optical_channel.frequency_slot)
    ))
  ,
  DESCRIPTOR = _OPTICAL_CHANNEL,
  __module__ = 'sliceable_transceiver_sdm_service_pb2'
  # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.optical_channel)
  ))
_sym_db.RegisterMessage(optical_channel)
_sym_db.RegisterMessage(optical_channel.frequency_slot)

slice = _reflection.GeneratedProtocolMessageType('slice', (_message.Message,), dict(

  sliceid = _reflection.GeneratedProtocolMessageType('sliceid', (_message.Message,), dict(
    DESCRIPTOR = _SLICE_SLICEID,
    __module__ = 'sliceable_transceiver_sdm_service_pb2'
    # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.slice.sliceid)
    ))
  ,

  optical_channel = _reflection.GeneratedProtocolMessageType('optical_channel', (_message.Message,), dict(
    DESCRIPTOR = _SLICE_OPTICAL_CHANNEL,
    __module__ = 'sliceable_transceiver_sdm_service_pb2'
    # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.slice.optical_channel)
    ))
  ,

  optical_signal = _reflection.GeneratedProtocolMessageType('optical_signal', (_message.Message,), dict(
    DESCRIPTOR = _SLICE_OPTICAL_SIGNAL,
    __module__ = 'sliceable_transceiver_sdm_service_pb2'
    # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.slice.optical_signal)
    ))
  ,
  DESCRIPTOR = _SLICE,
  __module__ = 'sliceable_transceiver_sdm_service_pb2'
  # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.slice)
  ))
_sym_db.RegisterMessage(slice)
_sym_db.RegisterMessage(slice.sliceid)
_sym_db.RegisterMessage(slice.optical_channel)
_sym_db.RegisterMessage(slice.optical_signal)

sliceid = _reflection.GeneratedProtocolMessageType('sliceid', (_message.Message,), dict(
  DESCRIPTOR = _SLICEID,
  __module__ = 'sliceable_transceiver_sdm_service_pb2'
  # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.sliceid)
  ))
_sym_db.RegisterMessage(sliceid)

transceiver = _reflection.GeneratedProtocolMessageType('transceiver', (_message.Message,), dict(

  slice = _reflection.GeneratedProtocolMessageType('slice', (_message.Message,), dict(
    DESCRIPTOR = _TRANSCEIVER_SLICE,
    __module__ = 'sliceable_transceiver_sdm_service_pb2'
    # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.transceiver.slice)
    ))
  ,
  DESCRIPTOR = _TRANSCEIVER,
  __module__ = 'sliceable_transceiver_sdm_service_pb2'
  # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.transceiver)
  ))
_sym_db.RegisterMessage(transceiver)
_sym_db.RegisterMessage(transceiver.slice)

transceiver_state = _reflection.GeneratedProtocolMessageType('transceiver_state', (_message.Message,), dict(

  slice = _reflection.GeneratedProtocolMessageType('slice', (_message.Message,), dict(
    DESCRIPTOR = _TRANSCEIVER_STATE_SLICE,
    __module__ = 'sliceable_transceiver_sdm_service_pb2'
    # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.transceiver_state.slice)
    ))
  ,
  DESCRIPTOR = _TRANSCEIVER_STATE,
  __module__ = 'sliceable_transceiver_sdm_service_pb2'
  # @@protoc_insertion_point(class_scope:sliceable_transceiver_sdm_service.transceiver_state)
  ))
_sym_db.RegisterMessage(transceiver_state)
_sym_db.RegisterMessage(transceiver_state.slice)


# @@protoc_insertion_point(module_scope)
